### ISSUE TITLE
详细的教程 detailed tutorials

### ISSUE THREAD

**Issue by eqfae** [ronardnx/hyprland_alpinelinux#1]
```
  471  git clone https://github.com/ronardnx/hyprland_alpinelinux && cd hyprland_alpinelinux && rm -rf .git && cp -r .local/* ~/.local/ && cp -r .config/* ~/.config/
  472  apk add git
  473  git clone https://github.com/ronardnx/hyprland_alpinelinux && cd hyprland_alpinelinux && rm -rf .git && cp -r .local/* ~/.local/ && cp -r .config/* ~/.config/
  474  ls
  475  cd ..
  476  ls
  477  ls -lha
  478  ls
  479  apk add hyprland
  480  apk add hyprland  waybar  rofi-wayland  nwg-look kitty kitty-kitten mate-polkit fish seatd
  481  apk add hyprland  waybar  rofi-wayland  kitty kitty-kitten mate-polkit fish seatd
  482  doas
  483  apk add doas
  484  fish
  485  chsh -s /usr/bin/fish
  486  reboot
  487  waybar
  488  poweroff
  489  df -h
  490  passwd
  491  useradd $USER seat
  492  apk add shadow
  493  useradd $USER seat
  494  useradd $USER seat
  495  apk add seatd
  496  useradd $USER seat
  497  echo $USER
  498  useradd $USER seat
  499  group 0
  500  groupadd -h
  501  groupadd seat
  502  groupadd video
  503  stty
  504  dbus-run-session Hyprland
  505  kitty
  506  dbus-run-session Hyprland
  507  history

```
先在虚拟机测试 成功后再安装到实体机 能否从一个干净的系统开始 用命令行搭配解说 或者脚本
有些命令没被记录 比如doas 是一个个单独运行的 hyprland是从testing分支安装的
我想要这种 https://www.bilibili.com/video/BV1m2421A75C/

Can we test this on a virtual machine and then install it on a physical machine, starting with a clean system, using the command line with commentary, or a script?
Some commands aren't documented, like doas, which is run individually, and hyprland, which is installed from the testing branch.
I'd like this https://www.bilibili.com/video/BV1m2421A75C/

**Comment by staticfrost** [comment]
any full guide would be appricated thanks.

**Comment by eqfae** [comment]
> any full guide would be appricated thanks.

现在用nixos 只是更新总是很大 但稳定 将二者的优点结合起来更好
Nowadays, just updates with nixos are always big but stable. It's better to combine the advantages of the two

**Comment by ronardnx** [comment]
> any full guide would be appricated thanks.

I alreadu gave you a guide. Lol.

**Comment by staticfrost** [comment]
If there was a written process from starting with a blank bare install to a follow riced out version that would be appricated.

**Comment by eqfae** [comment]
> If there was a written process from starting with a blank bare install to a follow riced out version that would be appricated.

现在用nixos 
alpine 你实际用edge源才是最新的 当时在edge源升级kde 桌面卡死 重启黑屏
nixos比较稳定 最新的是arch hyprland vscode那些更新很快 nixos合并慢些 但要很久才会推送到unstable
我现在服务器1台nixos 1台alpine 
Now use nixos
alpine, the actual use of edge source is the latest. At that time, when you upgraded edge source, the kde desktop was stuck and restarted the black screen.
Nixos is relatively stable. The latest is arch hyprland vscode. Those updates are fast. Nixos merge slowly, but it will take a long time to be pushed to unstable.
I now have 1 nixos and 1 alpine server

alpine 很小 
nixos 今天更新了近4g vscode hy等等 alpine全部安装可能比这还小 
alpine is small
Nixos updated nearly 4g vscodehy today, etc. All alpine installations may be smaller than this
